# Secondary dockerfile to skip the build when executed after ng build by travis
##STAGE 0, copying build from the dist folder to nginx
FROM nginx:stable-alpine

#Serving the production build with nginx
COPY /dist/iot-webclient /usr/share/nginx/html

#Applying custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

#Starting on localhost:80
CMD ["nginx", "-g", "daemon off;"]