version: '3.7'

services:
  leo-iot-web:
    depends_on: [ leo-iot-db, leo-iot-server ]
    image: docker.pkg.github.com/htl-leonding-project/leo-iot/leo-iot-web
    container_name: leo-iot-web
    ports:
      - 80:80
  leo-iot-server:
    depends_on: [leo-iot-db]
    image: docker.pkg.github.com/htl-leonding-project/leo-iot/leo-iot-server
    container_name: leo-iot-server
    ports:
      - "8080:8080"  # the HTTP endpoint
  leo-iot-db:
    image: docker.pkg.github.com/htl-leonding-project/leo-iot/leo-iot-db
    container_name: leo-iot-db
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: db
    volumes:
      - ./database/db/:/var/lib/postgresql/data
    ports:
      - 5432:5432
