version: '3.7'

services:
#  leo-iot-web-old:
#    depends_on: [ leo-iot-db, leo-iot-server ]
#    image: docker.pkg.github.com/htl-leonding-project/leo-iot/leo-iot-web-old
#    build: web-old
#    container_name: leo-iot-web-old
#    ports:
#      - 80:80
#  leo-iot-server:
#    depends_on: [leo-iot-db]
#    image: docker.pkg.github.com/htl-leonding-project/leo-iot/leo-iot-server
#    build: backend
#    container_name: leo-iot-server
#    ports:
#      - "8080:8080"  # the HTTP endpoint
  leo-iot-db:
    image: docker.pkg.github.com/htl-leonding-project/leo-iot/leo-iot-db
    build: database
    container_name: leo-iot-db
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: db
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
