= Getting Started
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left


== Clone Repository

[source, shell]
----
git clone https://github.com/htl-leonding-project/leo-iot
----

== Getting Started Development

=== Start Timescale DB

The production databse and the development database are the same. There is a extra docker-compose file for starting only the database. This container can be executed by running the following commands.

[source,shell]
----
cd database
docker-compose up -d
----

NOTE: -d option is for daemon. If you don't want to start it in the background, remove this option.

=== Start Quarkus in development Mode

For starting quarkus simply start quarkus in the development. This works with the following command

[source,shell]
----
cd backend
./mvnw clean compile quarkus:dev
----

=== Start Angular in development Mode

The frontend can be started in development mode with the start npm script.

[source,shell]
----
cd frontend
npm start
----

== Getting Started Production

=== Build

This command is for building the whole project. It will produce a docker image for every component.

[source,shell]
----
docker-compose build
----

=== Start

This will start the whole application with frontend, backend etc.

[source,shell]
----
docker-compose up -d
----

NOTE: -d option is for daemon. If you don't want to start it in the background, remove this option.
