= GitHub Secrets
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc]
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template]
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]

== Intro

In this Document all GitHub secrets are documented. Github Secrets are encrypted secrets stored on GitHub. These can be used in GitHub Actions. Don't confuse them with link:https://htl-leonding-project.github.io/leo-iot/git-secret[git secret].

== Change and create them on GitHub

You can configure those secrets link:https://github.com/htl-leonding-project/leo-iot/settings/secrets/actions[here]. If you dont have access to this page ask one of the administrator of the repository or the supervisor.

== Current Secrets (12.05.2021)

=== DEPIP

The ip of the machine which hosts the leo-iot application.

=== DEPKEY

The key for connecting to the host machine.

==== Create such key

connect to the host machine and navigate in the `~/.ssh` directory and execute the following command.

[source, bash]
----
ssh-keygen -t rsa
----

Select a name for the key and leave passphrase empty. This will produce a private and public key. Use the following command to attach the public key to the authorized keys.

[source, bash]
----
cat ~/.ssh/<key-name>.pub >> ~/.ssh/authorized_keys
----

IMPORTANT: Use the public key with the .pub ending not the private key

* `<key-name>`: the name of the key you specified

The remaining unused private key ist the key for the GitHub `DEPKEY` Secrets field.

.source
https://htl-leonding-college.github.io/quarkus-jar-gh-actions-demo/gh-actions.html

=== DEPUSER

The hostname of the host machine.

=== GSPRIVKEY

A gpg key which can access the link:git-secret[git secrets].

=== REGTOKEN

A personal access token which can access packages for the repository. link:https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token[Here] you can see how you create such token.

IMPORTANT: Make shure you check the packages read and write permission

=== REGUSER

The user associated with the token.
