#.travis.yml
sudo: required

addons:
  chrome: stable
services:
  - docker

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

#installing angular and docs generator
before_script:
  - npm install -g @angular/cli
  - npm install -g @compodoc/compodoc

#executing angular tests, production build and docs generation
script:
  #executing angular test and generating the coverage report
  - ng test --code-coverage --browsers=ChromeHeadless
  #building the app for production
  - ng build --prod
  #generating the documentation with compodoc
  - compodoc -p src/tsconfig.app.json -d ./docs
  #copying static assets to the generated directory
  - cp -R .github ./docs

after_success:
  #sending coverage report to codacy
  - npm run codacy-coverage-report
  - docker --version
  #credentials are encrypted and can be changed in travis web project/settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  #building image with name: iot-webclient(:latest, default tag)
  - docker build -t iot-webclient .
  #tagging with dockerhub repo
  - docker tag iot-webclient $DOCKER_USERNAME/iot-webclient
  #push the image to dockerhub
  - docker push $DOCKER_USERNAME/iot-webclient

#deploying docs to ghpages
deploy:
  provider: pages
  local-dir: ./docs
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  on:
    branch: master

notifications:
  email:
    recipients:
      - kaindl745@gmail.com
    on_failure: always
    on_success: change